'use client'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useEffect, useState } from 'react'
import { ArrowLeft, BarChart3, Loader2, Share2 } from 'lucide-react'

type PollOption = { text: string; imageData?: string | null }
type Poll = { id: number; question: string; options: PollOption[]; counts: number[]; totalVotes: number; time: string; imageData?: string | null }
function normalizePoll(poll: any): Poll { return { ...poll, id: Number(poll.id), options: Array.isArray(poll.options) ? poll.options.map((o: any) => typeof o === 'string' ? { text: o, imageData: null } : { text: String(o?.text ?? ''), imageData: o?.imageData ?? null }) : [], counts: Array.isArray(poll.counts) ? poll.counts.map(Number) : [], totalVotes: Number(poll.totalVotes ?? 0) } }
export default function SharedPollPage() {
  const { id } = useParams<{ id: string }>()
  const [poll, setPoll] = useState<Poll | null>(null); const [error, setError] = useState(''); const [voted, setVoted] = useState<number | null>(null)
  useEffect(() => { try { const saved=JSON.parse(localStorage.getItem('fowzan-poll-votes')||'{}'); if(saved[id]!==undefined)setVoted(Number(saved[id])) } catch {} ; fetch(`/api/messages?view=poll&id=${encodeURIComponent(id)}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'This poll could not be found.');setPoll(normalizePoll(d.poll))}).catch(e=>setError(e instanceof Error?e.message:'This poll could not be found.')) },[id])
  async function vote(i:number){ if(!poll||voted!==null)return; let key=localStorage.getItem('fowzan-anonymous-voter'); if(!key){key=crypto.randomUUID();localStorage.setItem('fowzan-anonymous-voter',key)} const r=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'vote-poll',pollId:poll.id,optionIndex:i,voterKey:key})}); const d=await r.json(); if(!r.ok){setError(d.error||'Could not vote.');return};setPoll({...poll,counts:d.counts,totalVotes:d.totalVotes});setVoted(i);try{const saved=JSON.parse(localStorage.getItem('fowzan-poll-votes')||'{}');saved[poll.id]=i;localStorage.setItem('fowzan-poll-votes',JSON.stringify(saved))}catch{}}
  async function share(){const url=window.location.href;if(navigator.share)await navigator.share({title:"A poll from Fowzan's Inbox",text:poll?.question,url});else await navigator.clipboard.writeText(url)}
  return <main className="shared-thread-page"><div className="shared-thread-grid" aria-hidden="true"/><section className="shared-thread-shell"><Link href="/" className="shared-thread-back"><ArrowLeft size={15}/> Fowzan&apos;s Inbox</Link>{!poll&&!error&&<div className="shared-thread-loading"><Loader2 className="spin" size={20}/> opening poll…</div>}{error&&<div className="shared-thread-card"><BarChart3 size={24}/><h1>Poll unavailable</h1><p>{error}</p><Link href="/" className="primary-button">Visit the inbox</Link></div>}{poll&&<article className="shared-thread-card"><div className="shared-thread-kicker"><span/> SHARED POLL <button onClick={share} aria-label="Share this poll"><Share2 size={15}/></button></div><h1>{poll.question}</h1>{poll.imageData&&<img className="poll-wall-image shared-poll-image" src={poll.imageData} alt="Poll visual" /> }<div className="poll-options shared-poll-options">{poll.options.map((o,i)=>{const pct=poll.totalVotes?Math.round(poll.counts[i]/poll.totalVotes*100):0;return <button key={`${o.text}-${i}`} className={`poll-option ${voted!==null?'show-result':''} ${voted===i?'selected':''}`} onClick={()=>vote(i)} disabled={voted!==null}><span className="poll-option-content">{o.imageData&&<img src={o.imageData} alt="" loading="lazy"/>}<span className="poll-option-label">{o.text}</span></span>{voted!==null&&<><i style={{width:`${pct}%`}}/><b>{pct}%</b></>}</button>})}</div><div className="poll-foot"><span>{poll.totalVotes} anonymous {poll.totalVotes===1?'vote':'votes'}</span><button className="ghost-button" onClick={share}><Share2 size={13}/> share</button></div></article>}</section></main>
}
